### ISSUE TITLE
1.19.2/3商店全空

### ISSUE THREAD

**Issue by lytDARK** [JesKi13567/BedWars#2]
自带地图在1.19.2/3无法使用，三种商店内全空，10110223处无箱子

**Comment by lytDARK** [comment]
This is a bug.

**Comment by JesKi13567** [comment]
我明天发布beta1.2，到时候重新放置一下吧（）

**Comment by JesKi13567** [comment]
已更新，请查收

**Comment by lytDARK** [comment]
感谢作者，我试试1.19。
如果解决了就close了吧。

**Comment by JesKi13567** [comment]
注，因为是beta版，有bug会及时上传修复的，可以随时关注。
