### ISSUE TITLE
经典模式商店吞资源，无规律可复现

### ISSUE THREAD

**Issue by 6gdfg** [JesKi13567/BedWars#5]
使用商店购买物品时，有几率导致金锭消失。数据包版本：beta1.4，服务器版本：1.20.1。

**Comment by JesKi13567** [comment]
版本是beta1.4么，你看看你的客户端是否加了背包整理或类似模组。

**Comment by 6gdfg** [comment]
我的客户端有背包整理。我朋友用的lunar client不知道有没有，我们都遇到了这种问题。版本是beta1.4

**Comment by JesKi13567** [comment]
禁用背包整理模组后再试试？

**Comment by 6gdfg** [comment]
经实测使用原版依然会出bug。

**Comment by 6gdfg** [comment]
例如物品栏为 剑 64铁锭 2金 32铁锭 如果买16个羊毛 会变成 剑 64铁锭 28铁锭 金没了 实测绿宝石也会这样

**Comment by JesKi13567** [comment]
不幸的是，我确实无法复现。
实在吞物品的话建议用经验模式代替吧...

**Comment by 6gdfg** [comment]
我尝试录了个视频，是自己双开录制，第一个端暂时没出bug，第二个端就出bug了。

https://github.com/JesKi13567/BedWars/assets/115078566/600553a5-fe18-4458-8376-dec0f02f7035

**Comment by 6gdfg** [comment]
可以发现第一个端物品栏顺序是 铁 金 铁 铁。第二个端顺序是 金 铁 铁 铁，第二个端出了问题

**Comment by 6gdfg** [comment]
后面我又测试了好多次 发现这个bug出现没有规律...很奇怪

**Comment by JesKi13567** [comment]
顺序不是啥问题，可以忽略。
我正版盗版都测试了几遍，确实都是无规律出现的资源被吞，我beta1.5再用另外的方式修吧，但起码经验模式是好的。

**Comment by 6gdfg** [comment]
OK谢谢啦

**Comment by JesKi13567** [comment]
beta1.4.1已修复
